name: Deploy to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6
      - name: Authenticate to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          tenant: ${{ secrets.TENANT }}
      - name: Create storage account for Terraform state
        run: |
          AZURE_STORAGE_ACCOUNT_NAME="terraformtikspocstate"
          AZURE_LOCATION="switzerlandnorth"
          if ! az storage account show -n $AZURE_STORAGE_ACCOUNT_NAME; then
            az storage account create -n $AZURE_STORAGE_ACCOUNT_NAME -g $AZURE_RESOURCE_GROUP -l $AZURE_LOCATION --sku Standard_LRS
          fi
      - name: Initialize Terraform
        run: |
          AZURE_STORAGE_ACCOUNT_NAME="terraformtikspocstate"
          AZURE_STORAGE_ACCOUNT_KEY=$(az storage account keys list -n $AZURE_STORAGE_ACCOUNT_NAME --query "[0].value" -o tsv)
          terraform init -backend-config="storage_account_name=$AZURE_STORAGE_ACCOUNT_NAME" -backend-config="access_key=$AZURE_STORAGE_ACCOUNT_KEY"
      - name: Plan Terraform deployment
        run: terraform plan
      - name: Apply Terraform deployment
        run: terraform apply -auto-approve
